server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: /db/changelog/db.changelog-master.xml
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: userModule
          uri: http://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: bookModule
          uri: http://BOOK-API
          predicates:
            - Path=/books/**
        - id: assignmentModule
            uri: http://ASSIGNMENT-API
            predicates:
              - Path=/assignments/**

