--- 
server: 
  port: 8083
spring: 
  security:
    user:
      name: "user"
      password: "pass"
  cloud: 
    discovery:
      locator:
        enabled: true 
    gateway:
      routes:
        - id: user-api
          uri: lb://user-api
          predicates: 
          - Path=/users/**
          filters:
          - RewritePath=/users/(?<path>.*), /$\{path}
          
#   main: 
#     allow-bean-definition-overriding: true
#     web-application-type: reactive
jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      
feign:
  hystrix:
    enabled: true

