--- 
server: 
  port: 8083
spring: 
  cloud: 
    gateway: 
      routes: 
        - id: userModule
          predicates: 
            - Path=/users/**
          uri: "http://USER-SERVICE"
        - id: bookModule
          predicates: 
            - Path=/books/**
          uri: "http://BOOK-API"
        - id: assignmentModule
          predicates: 
            - Path=/assignments/**
          uri: "http://ASSIGNMENT-API"
  main: 
    allow-bean-definition-overriding: true
    web-application-type: reactive
jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad
