--- 
server: 
  port: 8083
spring: 
  security:
    user:
      name: "user"
      password: "pass"
  cloud: 
    gateway:
      routes: 
        - id: USER-API
          predicates: 
            - Path=/users/**
          uri: "http://USER-SERVICE"
    discovery:
      locator:
        enabled: true 
  main: 
    allow-bean-definition-overriding: true
    web-application-type: reactive
jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
