--- 
server: 
  port: 8083
spring: 
  security:
    user:
      name: "user"
      password: "pass"
  cloud: 
    gateway:
      discovery:
        locator:
          enabled: true 
  main: 
    allow-bean-definition-overriding: true
    web-application-type: reactive
jwt:
  secretKey: ecf1222c-88fd-47f3-988f-bdd78bade1ad

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
